Git-Articles completed
DursunER/my_news_project pull request #3
Opened 2022-09-06 18:28 UTC by DursunER

2022-09-07 08:34 UTC, douglashellowell commented on __tests__/news.test.js
> +        expect(articleObj).toEqual(article_3);
ideally you would not be sending back an `array` when there is only one article

change this line to 

```diff
-   const articleObj = res.body.article[0];
+   const articleObj = res.body.article;
```

2022-09-07 08:35 UTC, douglashellowell commented on __tests__/news.test.js
> +      });
excellent!

You don't need to be checking the `res.status` as you've already got the `.expect(404)` on `line 37` here

2022-09-07 08:36 UTC, douglashellowell commented
Good stuff so far!

You need one more error handling test on this endpoint - what if a user tried to fetch an article using an `article_id` that *wasn't a string*?

i.e `GET /api/articles/not-an-id`

2022-09-07 08:39 UTC, emilyb93 commented on __tests__/news.test.js
> +});
We need to have some more tests here. Theres some error handling that needs to happen whenever we give our user control over the request. Think about what could happen if;
- we request a review id that is way out of range (9999)
- we request a review id that is not a number ('/api/review/dogs')

2022-09-07 08:40 UTC, emilyb93 requested changes
More testing needed

2022-09-08 11:12 UTC, douglashellowell commented
ready to merge! 🚀

2022-09-08 11:20 UTC, merged